## Deliverable 2. Create a Customer Travel Destinations Map.

In [12]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [13]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,Khandyga,62.67,135.60,13.59,86,98,2.10,RU,2020-10-26 20:27:49,overcast clouds
1,Derzhavinsk,51.10,66.32,35.35,90,100,21.39,KZ,2020-10-26 20:27:49,overcast clouds
2,Bangassou,4.74,22.82,69.71,90,100,2.30,CF,2020-10-26 20:27:49,overcast clouds
3,Methoni,36.82,21.70,64.99,82,0,4.70,GR,2020-10-26 20:27:50,clear sky
4,Rikitea,-23.12,-134.97,75.34,85,100,19.24,PF,2020-10-26 20:27:50,light rain

In [14]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [15]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
4,Rikitea,-23.12,-134.97,75.34,85,100,19.24,PF,2020-10-26 20:27:50,light rain
5,Kavaratti,10.57,72.64,82.42,72,81,7.00,IN,2020-10-26 20:27:50,broken clouds
6,Miandrivazo,-19.52,45.47,78.82,62,0,5.66,MG,2020-10-26 20:27:50,clear sky
13,Hirara,24.80,125.28,76.62,70,94,15.95,JP,2020-10-26 20:27:52,overcast clouds
15,Castro,-24.79,-50.01,72.09,70,100,7.16,BR,2020-10-26 20:23:31,overcast clouds
18,Guadalajara,20.67,-103.33,88.00,23,40,0.83,MX,2020-10-26 20:25:50,scattered clouds
22,Souillac,-20.52,57.52,73.40,73,40,10.29,MU,2020-10-26 20:27:53,scattered clouds
23,Rawson,-43.30,-65.10,71.13,29,100,17.83,AR,2020-10-26 20:27:54,overcast clouds
26,Mangrol,21.12,70.12,82.18,63,0,1.72,IN,2020-10-26 20:27:54,clear sky
27,Hithadhoo,-0.60,73.08,83.16,66,17,6.53,MV,2020-10-26 20:27:54,few clouds

In [16]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City                   264
Lat                    264
Lng                    264
Max Temp               264
Humidity               264
Cloudiness             264
Wind Speed             264
Country                259
Date                   264
Current Description    264
dtype: int64

In [17]:
#testing
temp_filter = ((city_data_df['Max Temp'] <= max_temp) 
                   & (city_data_df['Max Temp'] >= min_temp))
test_cities_df = city_data_df.loc[temp_filter]

In [18]:
temp_filter

0      False
1      False
2      False
3      False
4       True
       ...
697    False
698    False
699    False
700     True
701     True
Name: Max Temp, Length: 702, dtype: bool

In [19]:
#testing
null_filter = test_cities_df['Country'].isnull()#.all(axis=1)
test_cities_df.loc[null_filter, :]

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
427,Okakarara,-20.58,17.43,78.30,31,99,19.06,NaN,2020-10-26 20:30:00,overcast clouds
445,Ongandjera,-17.88,15.07,78.51,26,25,11.63,NaN,2020-10-26 20:30:11,scattered clouds
564,Rehoboth,-23.32,17.08,76.95,28,97,10.33,NaN,2020-10-26 20:30:45,overcast clouds
627,Aranos,-24.13,19.12,73.60,40,55,10.54,NaN,2020-10-26 20:31:02,broken clouds
691,Rundu,-17.93,19.77,76.03,19,0,4.68,NaN,2020-10-26 20:31:20,clear sky

In [20]:
test_cities_df.count()

City                   264
Lat                    264
Lng                    264
Max Temp               264
Humidity               264
Cloudiness             264
Wind Speed             264
Country                259
Date                   264
Current Description    264
dtype: int64

In [21]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.count()

City                   259
Lat                    259
Lng                    259
Max Temp               259
Humidity               259
Cloudiness             259
Wind Speed             259
Country                259
Date                   259
Current Description    259
dtype: int64

In [22]:
# 5a. Create DataFrame called clean_hotel_df to store hotel names along with city, country, max temp, and coordinates.
clean_hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
clean_hotel_df["Hotel Name"] = ""
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Rikitea,PF,75.34,light rain,-23.12,-134.97,
5,Kavaratti,IN,82.42,broken clouds,10.57,72.64,
6,Miandrivazo,MG,78.82,clear sky,-19.52,45.47,
13,Hirara,JP,76.62,overcast clouds,24.80,125.28,
15,Castro,BR,72.09,overcast clouds,-24.79,-50.01,
18,Guadalajara,MX,88.00,scattered clouds,20.67,-103.33,
22,Souillac,MU,73.40,scattered clouds,-20.52,57.52,
23,Rawson,AR,71.13,overcast clouds,-43.30,-65.10,
26,Mangrol,IN,82.18,clear sky,21.12,70.12,
27,Hithadhoo,MV,83.16,few clouds,-0.60,73.08,

In [23]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in clean_hotel_df.iterrows():
    
# 6c. Get latitude and longitude from DataFrame

    lat = row["Lat"] 
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
        
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        clean_hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"] 
        print(hotels["results"][0]["name"])
    except (IndexError):
        print("Hotel not found... skipping.")

Pension Maro'i
Hotels in Lakshadweep Islands
Hôtel Arc En Ciel Miandrivazo
Hotel Atoll Emerald Miyakojima
CHACARA BAILLY
Hotel Aranzazú
Bils' Villa
Hotel Punta León
Hotel The Royal Honours
Scoop Guest House
Oceano
HAMDAN PLAZA HOTEL
Finch Bay Galapagos Hotel
Villa Enata
Sheraton Kauai Resort at Coconut Beach
Shandrani Beachcomber Resort & Spa
Grage Hotel Bengkulu
Mini Hotel Central
Maui Seaside Hotel
Hotel Jardin Real
Nabelchel Bungalows
Hilo Hawaiian Hotel
Ganesh Anand Catering services Baloda
Cj's Travellers Inn
الحاج سليمان الشترة
Pousada das Palmeiras
Playa Linda Hotel
Lamana Hotel
Hotel not found... skipping.
Kiat Ngong Wetland BUNGALOW
Chambres d'hôte "La Trinité"
Lidera
The Nesbitt Arms
Isles Sunset Lodge
Peoplesight Learning Center ( PLC )
AXIM BEACH RESORT AND SPA
Hotel not found... skipping.
ALETHEIA Appartement Sinnamary
Hotel not found... skipping.
Lorengau Harbourside Hotel
Ulkel Guest House
Volcano Sea View Tree House
Haajy Guest House 1
New century hotel
Camp Pasica
Hotel La Sougoun
Hotel Riza
Paradise Inn
Hotel Peace Land Ishigakijima
Hotel Caribe
Hotel not found... skipping.
Lake Guntersville Bed and Breakfast
Fengshui Residence
The Hamsa Resort
Hotel Jacaré
Habitation Jouissant
Marica Hills
La Ode Husein
Tortuga B&B
สุริยาค้าไม้
Ha'apai Beach Resort
Resguardo Indigena Maguare
Keleti Beach Resort
Mickeys Guest House
M.O.S. Logística - Filial Fortaleza
Amerian Catamarca Park Hotel
Lindos Princess Beach Hotel
Village Mianda Mutole
Nuli Sapi
Agan-Hotel
OlusHome
Shelly Bay Resort
Hotel not found... skipping.
Casa Hotel Victoria
"Plantation Bed and Breakfast
Super 8 by Wyndham Fortuna
Valle Aridane
Aston Pontianak Hotel & Convention Center
Mercan Hotel
Hôtel & Restaurant DIANA Ambilobe
Aquarius Boutique Hotel Sampit
Baymont by Wyndham Lazaro Cardenas
Nancy Montanes Bernardo
Pousada Porto De Canoas
Bungalow 63
Hôtel Le Dronmi
St. Joseph Thirumana mandapam
Nosso Hotel
Sur Plaza Hotel
Hostal San Isidro Oficial
INN NEW HORIZON
Hotel Citra
Jalu Hotel
Hotel not found... skipping.
Grand Dafam Bela Ternate
Pousada Porto Praia
SanBiz Lodge
Villa Cordillera
Apart Hotel Rio Xingu
Eureka Inn Trademark By Wyndham
OYO 1639 Penginapan Anggrek Syariah 1
Southern Beach Hotel & Resort Okinawa
INN CORNER RIVER - PRADO - BAHIA - HOUSING AND HOTEL
Hwange Colliery Guest House
Hotel Maria
Elijah Worjloh
Screensaver
Expeditions Ténére voyages
Holiday Inn Express & Suites Elk Grove Central - Hwy 99
Hotel not found... skipping.
Nusa Island Retreat
Bora-Bora Pearl Beach Resort & Spa
Abaco Beach Resort
Hotel not found... skipping.
Windvillage
Okra Leaf Guest House Syariah
Vitoria,es
Hotel Festival Plaza Rosarito
Cattleman's Rest Motor Inn
Hôtel Le Lagon
The Espiritu Hotel
Hotel not found... skipping.
Cititel Penang
Pension Oaoa
Lindsey Hôtel
Pondok Pesantren Al Muhajirin Atambua
Paradise Hotel
domicile de boubé TTK
Hotel Pousada Tropical
Hotel los Algarrobos
Dwaraka Hotel.
Hotel Bressan
Atlantis Hotel
Hotel not found... skipping.
The Ritz-Carlton, Half Moon Bay
Storyboard Beach Resort
Holiday Inn Express & Suites Pensacola W I-10
Salinas do Maragogi All Inclusive Resort
Hotel not found... skipping.
Pacifica Lighthouse, Trademark Collection by Wyndham
Osprey Beach Hotel
Fakhamat Al Orjoana Apartment
Hotel Capriccio Mauá
Hotel El Recreo
Jageshwer House
Masanga
Park Hotel Calama
Hotel not found... skipping.
Cititel Penang
Hotel Touring Club
Macs
Hotel Syariah CN Darussalam
Al Mumtaz Transport Jiwani
Habitacion Triple con baño y entrada privada
Aseel Hotel Apartment
Derogongan Residence
Posada Llovizna Rodríguez
La Belle Motel
Hotel not found... skipping.
فندق الرشيد
Casa Tia Villa
Rinconcito Verde
OYO 1577 Hotel Shree Hari Grand
El Medina
Erlyn’s Sta Rosa City Home
Osmani Hotel
H10 Taburiente Playa
Paihuen
Mercure Maceio Pajucara Hotel
Raybow International Hotel
Major Grand
Pirineos
Conrad Bora Bora Nui
Vahmoneh Lodge Vanimo
Cibele Cass
Luz del Sol
Hotel not found... skipping.
Grand Vilia Hotel
Hotel Cuenca
Swiss Belhotel Manokwari
Piaçabuçu News
Auberge du Routard
Hotel Vitória Palace
Taloa Heights
Hotel Arena Blanca
Hotel not found... skipping.
Hotel not found... skipping.
Hospedaje Ximens
Platinum Hotel
Comfort Inn Hotel
Hotel not found... skipping.
Hotel Ballast Wilmington, Tapestry Collection by Hilton
MR ODAME
Charme Hotel Guarujá
Container Inn Puerto Vallarta
Casa Laguna, Bed & Breakfast
Pousada dos Navegantes
Hotel hewa bora
Hotel Londres
Hotel not found... skipping.
Trump International Hotel & Tower Panama
Aqua Belloni Lodge
San Ramon Marriott
Pousada Través'cia
Hôtel Telwa Bungalow
Hotel New Tokyo
Boukarra Ali
Marriott's Ko Olina Beach Club
Isawad Resort
Daito Guest House
Bora Bora Nails & Spa C.A.
Hotel Náutico de Paita
FARS Hotel & Resorts
Kimbe Bay Hotel
shri shyam palace sironj
Quinta Samay
Hotel Wixel
Hotel Santika Luwuk
Lovers Point Inn
American Eagle Inn
Casa en venta Las Cruces Tejutla San Marcos
GResort
HS Hotsson Smart Acapulco
Embassy Suites by Hilton Huntsville Hotel & Spa
OYO 71911 Hotel Amber Palace
YASH HOTEL
Doha Marriott Hotel
Center Hotel Punta Alta
Amazonie Découverte SARL
Hotel not found... skipping.
Kudahuvadhoo Retreat
Oustaz Vame DIAKITE
Norma franco
Imans Hotel Daloa
Courtyard by Marriott Houma
Sea Star Beau Rivage Hotel
Lakatoro Palm Lodge
Hotel not found... skipping.
Kokopo Beach Bungalow Resort
JHS Palace Hotel
EPIC SANA Luanda
Puerto Delta Apartamentos
Hotel Los Arcos
Hotel Marti
campismo las palmas
Dhukurrdji Lodge
Hotel Viverde Las Tirajanas
Foyer ADM
Hotel not found... skipping.
Hotel Praia Morena
hotel luna del desierto
Hotel California Todos Santos
Hotel not found... skipping.
Hotel not found... skipping.
Hotel 5 Sóis
City Hotel
Hotel not found... skipping.
Hotel San Rafael
Hotel restaurants and tourist Misyaf

In [24]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Rikitea,PF,75.34,light rain,-23.12,-134.97,Pension Maro'i
5,Kavaratti,IN,82.42,broken clouds,10.57,72.64,Hotels in Lakshadweep Islands
6,Miandrivazo,MG,78.82,clear sky,-19.52,45.47,Hôtel Arc En Ciel Miandrivazo
13,Hirara,JP,76.62,overcast clouds,24.80,125.28,Hotel Atoll Emerald Miyakojima
15,Castro,BR,72.09,overcast clouds,-24.79,-50.01,CHACARA BAILLY
18,Guadalajara,MX,88.00,scattered clouds,20.67,-103.33,Hotel Aranzazú
22,Souillac,MU,73.40,scattered clouds,-20.52,57.52,Bils' Villa
23,Rawson,AR,71.13,overcast clouds,-43.30,-65.10,Hotel Punta León
26,Mangrol,IN,82.18,clear sky,21.12,70.12,Hotel The Royal Honours
27,Hithadhoo,MV,83.16,few clouds,-0.60,73.08,Scoop Guest House

In [25]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

FileNotFoundError: [Errno 2] No such file or directory: 'Vacation_Search/WeatherPy_vacation.csv'

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

In [ ]:
# test
test_df = hotel_df.iloc[0:2,  :]#.to_frame()
type(test_df)
test_df.columns

In [ ]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

test_df = hotel_df.iloc[0:2,  :]#.to_frame()
# 6b. Iterate through the hotel DataFrame.
for index, row in test_df.iterrows():
# # 6c. Get latitude and longitude from DataFrame

    lat = row["Lat"] 
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
         
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    print(hotels)
    print('\n\n')
#     # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
#     try:
#         hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
#     except (IndexError):
#         print("Hotel not found... skipping.")

In [ ]:
hotel_df